version: 2.1

executors:
  node-cypress:
    docker:
      - image: "cypress/browsers:node16.14.0-chrome99-ff97"

orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@2.1.0

jobs:

  test:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run tests
          command: yarn run test:unit

workflows:sample:
    jobs:
      - test
      - cypress/run:
          executor: "node-cypress"
          command: yarn run test:e2e --headless
          yarn: true